Feature: Successful user registration

    Scenario: User registers with a unique email
        Given I open the browser and navigate to "https://automationexercise.com"
        When I click on the element with selector "a[href='/login']"
        And I enter "Test User" into the input with selector "input[data-qa='signup-name']"
        And I enter "testuser{timestamp}@example.com" into the input with selector "input[data-qa='signup-email']"
        And I click on the element with selector "button[data-qa='signup-button']"
        Then I should see the text "Enter Account Information"
        Then I should see the text "Enter Account Information"
        When I select gender "Mr"
        And I enter "yourpassword" into the input with selector "#password"
        And I select "1" from dropdown with selector "#days"
        And I select "January" from dropdown with selector "#months"
        And I select "2000" from dropdown with selector "#years"
        And I check the checkbox with selector "#newsletter"
        And I check the checkbox with selector "#optin"
        And I enter "FirstName" into the input with selector "#first_name"
        And I enter "LastName" into the input with selector "#last_name"
        And I enter "Company" into the input with selector "#company"
        And I enter "Address" into the input with selector "#address1"
        And I enter "State" into the input with selector "#state"
        And I enter "City" into the input with selector "#city"
        And I enter "12345" into the input with selector "#zipcode"
        And I enter "1234567890" into the input with selector "#mobile_number"
        And I click on the element with selector "button[data-qa='create-account']"
        Then I should see the text "Account Created!"